# Generated by Django 4.1.6 on 2023-04-20 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=50)),
                ('mes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_price',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('oil_changing_price', models.CharField(max_length=30)),
                ('batteries', models.CharField(max_length=30)),
                ('engine_service', models.CharField(max_length=30)),
                ('tire_wheel', models.CharField(blank=True, max_length=30, null=True)),
                ('steering_suspension', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, default='IMG_0624.JPG', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app7.manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_Brand', models.CharField(max_length=30)),
                ('car_name', models.CharField(max_length=30)),
                ('cust_fname', models.CharField(max_length=25)),
                ('cust_lname', models.CharField(max_length=25)),
                ('cust_email', models.CharField(max_length=30)),
                ('cust_mobile', models.CharField(max_length=12)),
                ('dateTime', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('Services', models.TextField()),
                ('cost', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done'), ('Released', 'Released')], default='Pending', max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
